[package]
name = "matheriser"
version = "0.1.0"
authors = ["akkuankka <cwmckenzie02@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.0"
num = "0.4.0"